name: Remote SSH Linux do Clone-Repo
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        port: ${{secrets.PORT}}
        script: sudo kill -9 `sudo lsof -t -i:80` && rm -rf monga-applications-lab && git clone https://github.com/BrunoPolezaGomes/monga-applications-lab.git && sudo python3 monga-applications-lab/app.py

#script: sudo kill -9 `sudo lsof -t -i:80` && rm -rf monga-applications-lab && git pull https://github.com/BrunoPolezaGomes/monga-applications-lab.git && sudo python3 monga-applications-lab/app.py